In [3]:
import numpy as np

In [4]:
"""
Numpy Array Attrubutes
"""

print(np.arange(3))
print(np.arange(3,9))
print(np.arange(3,9,2))

[0 1 2]
[3 4 5 6 7 8]
[3 5 7]


In [5]:
arr1 = np.random.randint(100, size = 6)
print(arr1)



[53 19 17 38  6 19]


In [36]:

np.random.seed(0)
arr = np.random.randint(10, size=(3,4))
print(arr)

print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
2
(3, 4)
12
int32
4
48


In [35]:
d = np.array([[5, 0, 3, 3],
 [7, 9, '4', 5],
 [2, 4, 7, 6]])

print(d[:22])
print(d.size)
print(d.dtype)
print(d.itemsize)
print(d.nbytes) 

[['5' '0' '3' '3']
 ['7' '9' '4' '5']
 ['2' '4' '7' '6']]
12
<U11
44
528


In [46]:
"""
Slicing
"""

arr = np.arange(10)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [51]:
arr = np.array([[6, 9, 4, 1, 5, 9, 7, 1],
      [3, 5, 7, 3, 6, 6, 7, 9],
      [1, 9, 6, 0, 3, 8, 4, 1],
      [4, 5, 0, 3, 1, 4, 4, 4],
      [0, 0, 8, 4, 6, 9, 3, 3],
      [2, 1, 2, 1, 3, 4, 1, 1]])

print(arr[:2, :3])

print(arr[:3, ::2])

[[6 9 4]
 [3 5 7]]
[[6 4 5 7]
 [3 7 6 7]
 [1 6 3 4]]


In [91]:
np.random.seed(3)
arr = np.random.randint(10, size=(6,8))

print(arr)

arr_sub = arr[:2, :2]
print(arr_sub)



[[8 0 1 6 5 6 5 0]
 [5 1 6 0 3 0 7 4]
 [9 6 1 7 8 6 5 2]
 [1 5 4 3 0 3 2 5]
 [6 1 0 6 6 0 5 1]
 [0 3 2 7 1 9 3 2]]
[[8 0]
 [5 1]]


In [97]:
np.random.seed(1124)
arr = np.random.randint(10, size=(6,8))

print(arr)

arr_sub = arr[:2, :2].copy()

print(arr_sub)

arr_sub[0,0] = 99

print(arr)
print(arr_sub)

[[8 0 1 6 5 6 5 0]
 [5 1 6 0 3 0 7 4]
 [9 6 1 7 8 6 5 2]
 [1 5 4 3 0 3 2 5]
 [6 1 0 6 6 0 5 1]
 [0 3 2 7 1 9 3 2]]
[[8 0]
 [5 1]]
[[8 0 1 6 5 6 5 0]
 [5 1 6 0 3 0 7 4]
 [9 6 1 7 8 6 5 2]
 [1 5 4 3 0 3 2 5]
 [6 1 0 6 6 0 5 1]
 [0 3 2 7 1 9 3 2]]
[[99  0]
 [ 5  1]]


In [102]:
arr = np.arange(1, 10)
print(arr, '\n')

# grid = np.reshape(arr, (3,3))
grid = arr.reshape(3,3)

print(grid)

[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [107]:
arr = np.array([1,2,3])
print(arr)

arr_new = arr[np.newaxis, :]
print(arr_new)

arr_new = arr[:, np.newaxis]
print(arr_new)

[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]


In [40]:
arr_1 = np.array([[1, 2, 3],[1,2,3]])
arr_2 = np.array([[4,5,6],[4,5,6]])
arr_3 = np.array([[7,8,9],[7,8,9]])

arr_total = np.concatenate([arr_1, arr_2, arr_3], axis=1)
print(arr_total)

arr_total2 = np.vstack([arr_1, arr_2, arr_3])
print(arr_total2)

arr_total3 = np.hstack([arr_1, arr_2, arr_3])
print(arr_total3)

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]
[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]


In [121]:
"""
Spliting
"""

# arr = np.random.randint(10, size=(1,10))
arr = [1,2,3,99,99,3,2,1]

print(arr)

arr_1, arr_2, arr_3 = np.split(arr, [3,5])

print(arr_1)
print(arr_2)
print(arr_3)

[1, 2, 3, 99, 99, 3, 2, 1]
[1 2 3]
[99 99]
[3 2 1]
