In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
lst = [1,2,3,4]

arr = np.array(lst)
print(arr)
print(type(arr))
print(lst.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>


AttributeError: 'list' object has no attribute 'dtype'

In [12]:
print(arr.dtype)
a = np.array([1, 2, "1.1, 1.2, 2.5"])
print(a.dtype)


int32
<U13


In [17]:
from sys import getsizeof

lst = [1]

print(getsizeof(lst))

arr = np.array([1]) #96 -> 100 int = 4byte
print(getsizeof(arr))

64
100


In [20]:
prices = [30,25,40,20,20,35,50,35]
price_arr = np.array(prices)

new_prices = [price - 5 for price in prices]
print(new_prices)

price_arr -= 5
print(price_arr)

[25, 20, 35, 15, 15, 30, 45, 30]
[25 20 35 15 15 30 45 30]


In [24]:
test_1 = np.array([92,94,88,91,87])
test_2 = np.array([79,100,86,93,91])
test_3 = np.array([87,85,72,90,92])

test_3_fix = test_3 + 2
print(test_3_fix)

total_grade = test_1 + test_2 + test_3_fix
print(total_grade)

final_grade = total_grade / 3
print(final_grade)

student_scores = np.array([test_1, test_2, test_3_fix])
print(student_scores.shape)

[89 87 74 92 94]
[260 281 248 276 272]
[86.66666667 93.66666667 82.66666667 92.         90.66666667]
(3, 5)


In [29]:
jeremy_test_2 = student_scores[1,3]
print(jeremy_test_2)

m_a_test_1 = np.array([student_scores[0,1], student_scores[0, 2]])
print(m_a_test_1)

print(student_scores[:,4])
print(student_scores[:,-1])

93
[94 88]
[87 91 94]
[87 91 94]


In [35]:
a = np.array([10,2,2,4,5,3,9,8,9,7])
mask = a>5
print(mask)

selected = a[a>5]
print(selected)

selected2 = a[(a>5) | (a<4)]
print(selected2)

[ True False False False False False  True  True  True  True]
[10  9  8  9  7]
[10  2  2  3  9  8  9  7]


In [45]:
porridge = np.array([79, 65, 50, 63,56,90,85,98,79,51])

cold = np.array(porridge[(porridge<60)])

hot = np.array(porridge[(porridge>80)])

just_right = np.array(porridge[(porridge>60) & (porridge<80)])

print(cold)
print(hot)
print(just_right)

[50 56 51]
[90 85 98]
[79 65 63 79]
