In [1]:
import numpy as np

In [2]:
def com_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [6]:
values = np.random.randint(1, 10, size =5)

print(values)

print(com_reciprocals(values))

[4 1 9 3 3]
[0.25       1.         0.11111111 0.33333333 0.33333333]


In [8]:
big_array = np.random.randint(1, 100, size = 1000000)

%timeit com_reciprocals(big_array)

2.21 s ± 18.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [10]:
%timeit 1 / big_array

2.32 ms ± 37.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [12]:
np.random.seed(1)
arr1 = np.random.randint(10, size = 5)
arr2 = np.random.randint(10, size = 5)
print(arr1, arr2)

[5 8 9 5 0] [0 1 7 6 9]


In [14]:
arr1 = arr1 - 2
print(arr1)

arr3 = arr1 + arr2
print(arr3)

arr4 = np.random.randint(10, size = (3,5))
print(arr4)

[ 1  4  5  1 -4]
[ 1  5 12  7  5]
[[9 7 6 9 1]
 [0 1 8 8 3]
 [9 8 7 3 6]]


In [17]:
x = np.array([-2,-1,0,1,2])

print(np.abs(x))

x = np.array([3-4j,4-3j,2+0j,0+1j])
print(np.abs(x))

[2 1 0 1 2]
[5. 5. 2. 1.]


In [23]:
theta = np.linspace(0, np.pi, 3)

print(theta)

print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [25]:
x = np.arange(1,5)

print(x)

aggr = np.add.reduce(x)
print(aggr)

aggr = np.multiply.reduce(x)
print(aggr)

[1 2 3 4]
10
24


In [29]:
x = np.arange(1,15)

print(x)

accum = np.multiply.accumulate(x)
print(accum)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[         1          2          6         24        120        720
       5040      40320     362880    3628800   39916800  479001600
 1932053504 1278945280]


In [31]:
np.random.seed(5)
arr = np.random.randint(10, size = (3,4))

print(arr)

print(np.sum(arr, axis = 1))

[[3 6 6 0]
 [9 8 4 7]
 [0 0 7 1]]
[15 28  8]
